version: '3'
services:
  backend:
    build: ./server
    image: dilus1322747/backend
    restart: always
    container_name: node-api1
    ports:
      - "5000:5000"
    networks:
      - mern-network  
    stdin_open: true
    tty: true
    depends_on:
      - mongo

  frontend:
    build: ./client
    image: dilus1322747/frontend
    container_name: react-ui1
    ports:
      - "3000:3000"
    networks:
      - mern-network  
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: mongo-db1
    ports:
      - "27017:27017"
    networks:
      - mern-network  

networks:
  mern-network:
    driver: bridge
