/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 basic_shirt.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/basic_shirt.glb')
  return (
    <group {...props} dispose={null} scale={[-0.2,-0.2,-0.2]}>
      <group position={[0.007, 1.522, 0.072]} rotation={[1.194, -0.055, -0.176]} scale={[0.55, 1, 0.55]}>
        <mesh geometry={nodes.Button_836348_1.geometry} material={materials['Default Button_2443820']} />
        <mesh geometry={nodes.Button_836348_2.geometry} material={materials['Default Button_2443820']} />
      </group>
      <group position={[0.008, 1.434, 0.095]} rotation={[1.332, 0.01, -0.145]} scale={[0.55, 1, 0.55]}>
        <mesh geometry={nodes.Button_836567_1.geometry} material={materials['Default Button_2443820']} />
        <mesh geometry={nodes.Button_836567_2.geometry} material={materials['Default Button_2443820']} />
      </group>
      <group position={[0.007, 1.344, 0.11]} rotation={[1.418, -0.016, -0.025]} scale={[0.55, 1, 0.55]}>
        <mesh geometry={nodes.Button_836747_1.geometry} material={materials['Default Button_2443820']} />
        <mesh geometry={nodes.Button_836747_2.geometry} material={materials['Default Button_2443820']} />
      </group>
      <group position={[0.006, 1.253, 0.123]} rotation={[1.42, -0.007, 0.028]} scale={[0.55, 1, 0.55]}>
        <mesh geometry={nodes.Button_837044_1.geometry} material={materials['Default Button_2443820']} />
        <mesh geometry={nodes.Button_837044_2.geometry} material={materials['Default Button_2443820']} />
      </group>
      <group position={[0.006, 1.163, 0.134]} rotation={[1.469, 0.001, 0.07]} scale={[0.55, 1, 0.55]}>
        <mesh geometry={nodes.Button_837202_1.geometry} material={materials['Default Button_2443820']} />
        <mesh geometry={nodes.Button_837202_2.geometry} material={materials['Default Button_2443820']} />
      </group>
      <group position={[0.007, 1.072, 0.137]} rotation={[1.517, 0.007, 0.048]} scale={[0.55, 1, 0.55]}>
        <mesh geometry={nodes.Button_837327_1.geometry} material={materials['Default Button_2443820']} />
        <mesh geometry={nodes.Button_837327_2.geometry} material={materials['Default Button_2443820']} />
      </group>
      <group position={[0.295, 0.971, -0.04]} rotation={[1.362, 0.104, 2.764]} scale={[0.55, 1, 0.55]}>
        <mesh geometry={nodes.Button_881672_1.geometry} material={materials['Default Button_2443820']} />
        <mesh geometry={nodes.Button_881672_2.geometry} material={materials['Default Button_2443820']} />
      </group>
      <group position={[0.332, 0.973, -0.04]} rotation={[1.456, 0.154, -2.086]} scale={[0.55, 1, 0.55]}>
        <mesh geometry={nodes.Button_881723_1.geometry} material={materials['Default Button_2443820']} />
        <mesh geometry={nodes.Button_881723_2.geometry} material={materials['Default Button_2443820']} />
      </group>
      <group position={[0.319, 1.059, -0.057]} rotation={[1.395, 0.108, -2.426]} scale={[0.55, 1, 0.55]}>
        <mesh geometry={nodes.Button_1002682_1.geometry} material={materials['Default Button_2443820']} />
        <mesh geometry={nodes.Button_1002682_2.geometry} material={materials['Default Button_2443820']} />
      </group>
      <group position={[-0.276, 1.045, -0.091]} rotation={[1.38, -0.032, 2.585]} scale={[0.55, 1, 0.55]}>
        <mesh geometry={nodes.Button_1031674_1.geometry} material={materials['Default Button_2443820']} />
        <mesh geometry={nodes.Button_1031674_2.geometry} material={materials['Default Button_2443820']} />
      </group>
      <group position={[-0.25, 0.956, -0.079]} rotation={[1.666, -0.058, -2.958]} scale={[0.55, 1, 0.55]}>
        <mesh geometry={nodes.Button_1031681_1.geometry} material={materials['Default Button_2443820']} />
        <mesh geometry={nodes.Button_1031681_2.geometry} material={materials['Default Button_2443820']} />
      </group>
      <group position={[-0.287, 0.959, -0.072]} rotation={[1.495, -0.112, 2.187]} scale={[0.55, 1, 0.55]}>
        <mesh geometry={nodes.Button_1031688_1.geometry} material={materials['Default Button_2443820']} />
        <mesh geometry={nodes.Button_1031688_2.geometry} material={materials['Default Button_2443820']} />
      </group>
      <group position={[0.006, 1.588, 0.054]} rotation={[1.916, 0.373, -0.472]} scale={[0.55, 1, 0.55]}>
        <mesh geometry={nodes.Button_1133729_1.geometry} material={materials['Default Button_2443820']} />
        <mesh geometry={nodes.Button_1133729_2.geometry} material={materials['Default Button_2443820']} />
      </group>
      <mesh geometry={nodes.Topstitch_2343047_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_2343047_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_758744_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_758744_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_789233_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_789233_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_881119_1.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_881119_2.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_984796_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_984796_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1595700_1.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1595700_2.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1502808_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1502808_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1533442_1.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1533442_2.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_819951_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_819951_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_850422_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_850422_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_2217599_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_2217599_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_912134_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_912134_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_922735_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_922735_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1658157_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1658157_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1668758_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1668758_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1089131_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1089131_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1092094_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1092094_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1131173_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1131173_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1134136_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1134136_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1179297_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1179297_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1182260_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1182260_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1306842_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1306842_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1309705_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1309705_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1411064_1.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1411064_2.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1472250_1.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1472250_2.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1441723_1.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1441723_2.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_2343130_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_2343130_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1502891_1.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1502891_2.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1533525_1.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1533525_2.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1411147_1.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1411147_2.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1472253_1.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1472253_2.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1441726_1.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1441726_2.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_502578_1.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_502578_2.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes['1_2'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['1_3'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['1_4'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
  {/* front  right side mesh */}
      <mesh geometry={nodes['2_1'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
  <mesh geometry={nodes['2_2'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['2_3'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      {/*  right side cuff */}
      <mesh geometry={nodes['7_1'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['7_2'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['7_3'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      {/* front left side */}
      <mesh geometry={nodes['4_1'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['4_2'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['4_3'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['1_5'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['1_6'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['1_7'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['6_1'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['6_2'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['6_3'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['9_1'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['9_2'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['9_3'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['8_1'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['8_2'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['8_3'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['12_1'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['12_2'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['12_3'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
{/* left hand front */}      
      <mesh geometry={nodes['3_1'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['3_2'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['3_3'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['10_1'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['10_2'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['10_3'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['13_1'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['13_2'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['13_3'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['11_1'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['11_2'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['11_3'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
    </group>
  )
}

useGLTF.preload('/basic_shirt.glb')
