/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 basic_shirt_2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
export default function Model(props) {
  const { nodes, materials } = useGLTF('/basic_shirt_2.glb')
  return (
    <group {...props} dispose={null} scale={[0.75,0.75,0.75]}   >
      <mesh geometry={nodes['12'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['13'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes['9'].geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes.Back_Piece.geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes.Back_top_shoulder.geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes.Collar.geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes.Front_Left.geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes.Front_Right.geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes.L_Cuff.geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes.L_Sleeve.geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes.Pocket.geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes.R_Cuff.geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes.R_Sleeve.geometry} material={materials.Cotton_Heavy_Canvas_2443799} />
      <mesh geometry={nodes.Button_836348.geometry} material={materials['Default Button_2443820']} position={[0.007, 1.522, 0.072]} rotation={[1.194, -0.055, -0.176]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes.Button_836567.geometry} material={materials['Default Button_2443820']} position={[0.008, 1.434, 0.095]} rotation={[1.332, 0.01, -0.145]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes.Button_836747.geometry} material={materials['Default Button_2443820']} position={[0.007, 1.344, 0.11]} rotation={[1.418, -0.016, -0.025]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes.Button_837044.geometry} material={materials['Default Button_2443820']} position={[0.006, 1.253, 0.123]} rotation={[1.42, -0.007, 0.028]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes.Button_837202.geometry} material={materials['Default Button_2443820']} position={[0.006, 1.163, 0.134]} rotation={[1.469, 0.001, 0.07]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes.Button_837327.geometry} material={materials['Default Button_2443820']} position={[0.007, 1.072, 0.137]} rotation={[1.517, 0.007, 0.048]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes.Button_881672.geometry} material={materials['Default Button_2443820']} position={[0.295, 0.971, -0.04]} rotation={[1.362, 0.104, 2.764]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes.Button_881723.geometry} material={materials['Default Button_2443820']} position={[0.332, 0.973, -0.04]} rotation={[1.456, 0.154, -2.086]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes.Button_1002682.geometry} material={materials['Default Button_2443820']} position={[0.319, 1.059, -0.057]} rotation={[1.395, 0.108, -2.426]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes.Button_1031674.geometry} material={materials['Default Button_2443820']} position={[-0.276, 1.045, -0.091]} rotation={[1.38, -0.032, 2.585]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes.Button_1031681.geometry} material={materials['Default Button_2443820']} position={[-0.25, 0.956, -0.079]} rotation={[1.666, -0.058, -2.958]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes.Button_1031688.geometry} material={materials['Default Button_2443820']} position={[-0.287, 0.959, -0.072]} rotation={[1.495, -0.112, 2.187]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes.Button_1133729.geometry} material={materials['Default Button_2443820']} position={[0.006, 1.588, 0.054]} rotation={[1.916, 0.373, -0.472]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes.Topstitch_2343047.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_758744.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_789233.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_881119.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_984796.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1595700.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1502808.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1533442.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_819951.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_850422.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_2217599.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_912134.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_922735.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1658157.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1668758.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1089131.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1092094.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1131173.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1134136.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1179297.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1182260.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1306842.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1309705.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1411064.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1472250.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1441723.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_2343130.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1502891.geometry} material={materials['Default Topstitch Copy 1_2444159']} />
      <mesh geometry={nodes.Topstitch_1533525.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1411147.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1472253.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_1441726.geometry} material={materials['Default Topstitch_2444052']} />
      <mesh geometry={nodes.Topstitch_502578.geometry} material={materials['Default Topstitch_2444052']} />
    </group>
  )
}

useGLTF.preload('/basic_shirt_2.glb')
