/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 crop_top.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/crop_top.glb')
  return (
    <group {...props} dispose={null}  scale={[1,1,1]}>
      <mesh geometry={nodes.Pattern_24855_1.geometry} material={materials.Knit_Cotton_Jersey_23794} />
      <mesh geometry={nodes.Pattern_24855_2.geometry} material={materials.Knit_Cotton_Jersey_23794} />
      <mesh geometry={nodes.Pattern_24855_3.geometry} material={materials.Knit_Cotton_Jersey_23794} />
      <mesh geometry={nodes.Pattern_24856_1.geometry} material={materials.Knit_Cotton_Jersey_23794} />
      <mesh geometry={nodes.Pattern_24856_2.geometry} material={materials.Knit_Cotton_Jersey_23794} />
      <mesh geometry={nodes.Pattern_24856_3.geometry} material={materials.Knit_Cotton_Jersey_23794} />
      <mesh geometry={nodes.Pattern_36841_1.geometry} material={materials.Cotton_Gabardine_525685} />
      <mesh geometry={nodes.Pattern_36841_2.geometry} material={materials.Cotton_Gabardine_525685} />
      <mesh geometry={nodes.Pattern_36841_3.geometry} material={materials.Cotton_Gabardine_525685} />
      <mesh geometry={nodes.Pattern_117295_1.geometry} material={materials.Trim_Full_Grain_Leather_2639} />
      <mesh geometry={nodes.Pattern_117295_2.geometry} material={materials.Trim_Full_Grain_Leather_2639} />
      <mesh geometry={nodes.Pattern_117295_3.geometry} material={materials.Trim_Full_Grain_Leather_2639} />
      <mesh geometry={nodes.Pattern_200678_1.geometry} material={materials.Cotton_Canvas_2646} />
      <mesh geometry={nodes.Pattern_200678_2.geometry} material={materials.Cotton_Canvas_2646} />
      <mesh geometry={nodes.Pattern_200678_3.geometry} material={materials.Cotton_Canvas_2646} />
      <mesh geometry={nodes.Pattern_36842_1.geometry} material={materials.Cotton_Gabardine_525685} />
      <mesh geometry={nodes.Pattern_36842_2.geometry} material={materials.Cotton_Gabardine_525685} />
      <mesh geometry={nodes.Pattern_36842_3.geometry} material={materials.Cotton_Gabardine_525685} />
      <mesh geometry={nodes.Pattern_117296_1.geometry} material={materials.Trim_Full_Grain_Leather_2639} />
      <mesh geometry={nodes.Pattern_117296_2.geometry} material={materials.Trim_Full_Grain_Leather_2639} />
      <mesh geometry={nodes.Pattern_117296_3.geometry} material={materials.Trim_Full_Grain_Leather_2639} />
      <mesh geometry={nodes.Pattern_200679_1.geometry} material={materials.Cotton_Canvas_2646} />
      <mesh geometry={nodes.Pattern_200679_2.geometry} material={materials.Cotton_Canvas_2646} />
      <mesh geometry={nodes.Pattern_200679_3.geometry} material={materials.Cotton_Canvas_2646} />
    </group>
  )
}

useGLTF.preload('/crop_top.glb')
