/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 leander_tshirt.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/leander_tshirt.glb')
  return (
    <group {...props} dispose={null} scale={[0.8,0.8,0.8]}>
      <mesh geometry={nodes['L-SLEEVE'].geometry} material={materials.main_12888} />
      <mesh geometry={nodes.Pattern_1086885.geometry} material={materials.main_12888} />
      <mesh geometry={nodes.Pattern_2903483.geometry} material={materials['main Copy 1_12915']} />
      <mesh geometry={nodes['R-SLEEVE_1'].geometry} material={materials.main_12888} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-BACK'].geometry} material={materials['main_12888.002']} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-COL'].geometry} material={materials.main_12888} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-FRONT'].geometry} material={materials['main_12888.001']} />
      <mesh geometry={nodes.Stitch_389563.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13528} />
      <mesh geometry={nodes.Stitch_389563001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13537} />
      <mesh geometry={nodes.Stitch_389591.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13528} />
      <mesh geometry={nodes.Stitch_389591001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13537} />
      <mesh geometry={nodes.Topstitch_1642569.geometry} material={materials.ISO_101_Single_Thread_Chainstitch_2mmoffset_14908} />
      <mesh geometry={nodes.Topstitch_1642569001.geometry} material={materials.ISO_101_Single_Thread_Chainstitch_2mmoffset_14917} />
      <mesh geometry={nodes.Stitch_386715.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13528} />
      <mesh geometry={nodes.Stitch_386715001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13537} />
      <mesh geometry={nodes.Stitch_386743.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13528} />
      <mesh geometry={nodes.Stitch_386743001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13537} />
      <mesh geometry={nodes.Stitch_392217.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13528} />
      <mesh geometry={nodes.Stitch_392217001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13537} />
      <mesh geometry={nodes.Stitch_392189.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13528} />
      <mesh geometry={nodes.Stitch_392189001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13537} />
    </group>
  )
}

useGLTF.preload('/leander_tshirt.glb')
