/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 leander_tshirt_decal.glb 
*/

import React, { useRef } from 'react'
import { Decal, useGLTF, useTexture } from '@react-three/drei'
import { degToRad } from "three/src/math/MathUtils.js";
import { useState } from 'react';
import { useControls } from 'leva';






export default function Model(props) {
  const { nodes, materials } = useGLTF('/leander_tshirt_decal.glb')




  const [rotation, setRotation] = useState([0, 0, 0]);
  const [image_size, setScale] = useState([0.50, 0.50, 0.10]);




  const meshRef = useRef();


let side=props.image_side


console.log(side)

 {/* useFrame(() => {
    if (meshRef.current) {
      meshRef.current.rotation.y += 0.05;
    }
  });
 */}

  useControls({
 
    image_size: {
        min: 0.1,
        max: 2,
        value: 0.10,
        step: 0.01,
        onChange: (value) => {
            setScale(() => [value, value, 1.5]);
        },
    },
});

useControls({
   
    angle2: {
        min: degToRad(0),
        max: degToRad(360),
        value: 0,
        step: 0.01,
        onChange: (value) => {
            const x = Math.sin(value);
            const z = Math.cos(value);
            const rot = Math.atan2(x, z);
            setRotation(() => [0, 0, rot]);
        },
    },
});





  return (
    <group {...props} dispose={null} scale={[0.8,0.8,0.8]}>
      <mesh geometry={nodes.Pattern_1086885.geometry} material={materials.main_2677} />
      <mesh geometry={nodes.Pattern_2903483.geometry} material={materials['main Copy 1_2693']} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-BACK'].geometry} material={materials.main_2677} >


      {
  props.back_image.map((imageUrl, index) => {



    console.log(`props.position ${props.back_position[index]}`)

    const decal = props.back_position ? props.back_position[index] : { x: 0, y: 0, z: 0.15 };

    const texture = useTexture(imageUrl);
   
    const { x, y, z } = decal;
    console.log(`x is ${x}`)
    console.log(`y is ${x}`)

    const newPosition = [x, y, z];

    console.log(index);
    console.log(`the decal is ${JSON.stringify(props.back_position[index])}`);
 console.log(newPosition); 

    return (
      <Decal key={index} position={newPosition} rotation={rotation} scale={image_size} map={texture} />
    );
  })
}


        </mesh>
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-COL'].geometry} material={materials.main_2677} />



      <mesh geometry={nodes['TSHIRTREGULARSSTGM-FRONT'].geometry} material={materials.main_2677} >
{

      props.front_image.map((imageUrl, index) => {



console.log(`props.position ${props.position1[index]}`)

const decal = props.position1 ? props.position1[index] : { x: 0, y: 0, z: 0.15 };


console.log(decal)

const texture = useTexture(imageUrl);

const { x, y, z } = decal;
console.log(`x is ${x}`)
console.log(`y is ${x}`)

const newPosition = [x, y, z];

console.log(index);
console.log(`the decal is ${JSON.stringify(props.position1[index])}`);
console.log(newPosition); 

return (
  <Decal key={index} position={newPosition} rotation={rotation} scale={image_size} map={texture} />
);
})

}

        </mesh>





      <mesh geometry={nodes['TSHIRTREGULARSSTGM-SLEEVE_LEFT'].geometry} material={materials.main_2677} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-SLEEVE_RISGHT'].geometry} material={materials.main_2677} >


      {


props.right_image.map((imageUrl, index) => {

  console.log("right position in decal")

console.log(`props.position ${props.right_position[index]}`)

const decal = props.right_position ? props.right_position[index] : { x: 0, y: 0, z: 0.15 };

const texture = useTexture(imageUrl);
console.log(texture)
const { x, y, z } = decal;
console.log(`x is ${x}`)
console.log(`y is ${x}`)

const newPosition = [x, y, z];

console.log(index);
console.log(`the decal is ${JSON.stringify(props.position1[index])}`);
console.log(newPosition); 

return (
<Decal key={index} position={[-0.2,-0.1,0]} rotation={rotation} scale={image_size} map={texture} />
);
})

}

        </mesh>
      <mesh geometry={nodes.Stitch_389563.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_2999} />
      <mesh geometry={nodes.Stitch_389563001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_3022} />
      <mesh geometry={nodes.Stitch_389591.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_2999} />
      <mesh geometry={nodes.Stitch_389591001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_3022} />
      <mesh geometry={nodes.Topstitch_1642569.geometry} material={materials.ISO_101_Single_Thread_Chainstitch_2mmoffset_3715} />
      <mesh geometry={nodes.Topstitch_1642569001.geometry} material={materials.ISO_101_Single_Thread_Chainstitch_2mmoffset_3738} />
      <mesh geometry={nodes.Stitch_386715.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_2999} />
      <mesh geometry={nodes.Stitch_386715001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_3022} />
      <mesh geometry={nodes.Stitch_386743.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_2999} />
      <mesh geometry={nodes.Stitch_386743001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_3022} />
      <mesh geometry={nodes.Stitch_392217.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_2999} />
      <mesh geometry={nodes.Stitch_392217001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_3022} />
      <mesh geometry={nodes.Stitch_392189.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_2999} />
      <mesh geometry={nodes.Stitch_392189001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_3022} />
    </group>
  )
}

useGLTF.preload('/leander_tshirt_decal.glb')
