/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 leo_tshirt.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/leo_tshirt.glb')
  return (
    <group {...props} dispose={null} scale={[0.7,0.7,0.7]}>
      <mesh geometry={nodes.Pattern_1086885.geometry} material={materials.main_2677} />
      <mesh geometry={nodes.Pattern_2903483.geometry} material={materials['main Copy 1_2693']} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-BACK'].geometry} material={materials.Material_Rear} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-COL'].geometry} material={materials.Material_Collar} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-FRONT'].geometry} material={materials.Material_Front} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-SLEEVE_LEFT'].geometry} material={materials.Material_R_Sleeve} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-SLEEVE_RISGHT'].geometry} material={materials.Material_L_Sleeve} />
      <mesh geometry={nodes.Stitch_389563.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_2999} />
      <mesh geometry={nodes.Stitch_389563001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_3022} />
      <mesh geometry={nodes.Stitch_389591.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_2999} />
      <mesh geometry={nodes.Stitch_389591001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_3022} />
      <mesh geometry={nodes.Topstitch_1642569.geometry} material={materials.ISO_101_Single_Thread_Chainstitch_2mmoffset_3715} />
      <mesh geometry={nodes.Topstitch_1642569001.geometry} material={materials.ISO_101_Single_Thread_Chainstitch_2mmoffset_3738} />
      <mesh geometry={nodes.Stitch_386715.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_2999} />
      <mesh geometry={nodes.Stitch_386715001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_3022} />
      <mesh geometry={nodes.Stitch_386743.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_2999} />
      <mesh geometry={nodes.Stitch_386743001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_3022} />
      <mesh geometry={nodes.Stitch_392217.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_2999} />
      <mesh geometry={nodes.Stitch_392217001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_3022} />
      <mesh geometry={nodes.Stitch_392189.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_2999} />
      <mesh geometry={nodes.Stitch_392189001.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_3022} />
    </group>
  )
}

useGLTF.preload('/leo_tshirt.glb')
