/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 poncho.glb 
*/

import React, { useEffect, useRef, useState } from 'react'
import { OrbitControls, useGLTF, useTexture } from '@react-three/drei'
import polyster from './second_design.jpg';
import axios from 'axios';
import { Buffer } from 'buffer';
import { useFrame } from '@react-three/fiber';

export default function Model(props) {

  const groupRef = useRef();

 {/* useFrame(({ clock }) => {
    const time = clock.getElapsedTime();

    if (time % 20 >= 0 && time % 20 < 10) {
     
      groupRef.current.rotation.y = time * 0.7;
    } else {
      
      groupRef.current.rotation.y = 0;
    }
  }); */}


  const[iamge_backend,setBackend_image]=useState()

  const[iamge_backend2,setBackend_image2]=useState()

    const [images, setImages] = useState([]);


  useEffect(() => {
    fetchImages();



    const interval = setInterval(fetchImages, 5000); // Fetch every 5 seconds

    return () => clearInterval(interval);
  }, []);



  useEffect(() => {
      const material = props.material; 
      images.forEach((image) => {
          if (material === image.name  && selected_part === "Upper Skirt") {
              console.log(image.name)
              let source = `data:image/${image.img.contentType};base64,${Buffer.from(image.img.data).toString('base64')}`
              setBackend_image(source);
          }
          if (material === image.name  && selected_part === "Lower Skirt") {
            console.log(image.name)
            let source = `data:image/${image.img.contentType};base64,${Buffer.from(image.img.data).toString('base64')}`
            setBackend_image2(source);
        }
      });
  }, [props.material, images]); 


  const fetchImages = async () => {
    try {
      //const response = await axios.get('http://13.201.251.105/:5000/send_image');http://localhost:5000/send_image
      const response = await axios.get('http://13.201.251.105/:5000/send_image');
      setImages(response.data);
    } catch (error) {
      console.error('Error fetching images:', error);
    }
  };




  let textureprops
  let texture
  if (iamge_backend) {
      textureprops = useTexture({
          map: iamge_backend,
      });
  }


  else if (iamge_backend2) {
    textureprops2 = useTexture({
        map: iamge_backend,
    });
}
  else {

      textureprops = useTexture({
          map: polyster,
      })

  }


const selected_part=props.part_selected

  const { nodes, materials } = useGLTF('/poncho.glb')
  return (
    
    <group  ref={groupRef}  {...props} dispose={null} scale={[0.60, 0.60, 0.60]}>

      <mesh geometry={nodes.Cloth_mesh.geometry} material={materials.Rib_2X2_468gsm_263076} />

      {/* head mesh */}
      <mesh geometry={nodes.Cloth_mesh_1.geometry} material={materials.Rib_2X2_468gsm_263076} >


</mesh>

      <mesh geometry={nodes.Cloth_mesh_2.geometry} material={materials.Rib_2X2_468gsm_263076} />
      <mesh geometry={nodes.Cloth_mesh_3.geometry} material={materials.Rib_2X2_468gsm_263076} />

      
      <mesh geometry={nodes.Cloth_mesh_4.geometry} material={materials.Rib_2X2_468gsm_263076} />
      
      <mesh geometry={nodes.Cloth_mesh_5.geometry} material={materials.Rib_2X2_468gsm_263076} />
      
      <mesh geometry={nodes.Cloth_mesh_6.geometry} material={materials.Rib_2X2_468gsm_263076} />
      
      <mesh geometry={nodes.Cloth_mesh_7.geometry} material={materials.Rib_2X2_468gsm_263076} />
      
      <mesh geometry={nodes.Cloth_mesh_8.geometry} material={materials.Rib_2X2_468gsm_263076} />
      

      {/* upper mesh */}
      <mesh geometry={nodes.Cloth_mesh_9.geometry} material={materials.Rib_2X2_468gsm_263076} >

      {selected_part === "Upper Skirt" && (
        <meshStandardMaterial {...textureprops} />
    )}
        </mesh>



      
      <mesh geometry={nodes.Cloth_mesh_10.geometry} material={materials.Rib_2X2_468gsm_263076} />

      
      <mesh geometry={nodes.Cloth_mesh_11.geometry} material={materials.Rib_2X2_468gsm_263076} />
      
      <mesh geometry={nodes.Cloth_mesh_12.geometry} material={materials.Rib_2X2_468gsm_263076} />
      
      <mesh geometry={nodes.Cloth_mesh_13.geometry} material={materials.Rib_2X2_468gsm_263076} />
      
      <mesh geometry={nodes.Cloth_mesh_14.geometry} material={materials.Rib_2X2_468gsm_263076} />
      
      <mesh geometry={nodes.Cloth_mesh_15.geometry} material={materials.Rib_2X2_468gsm_263076} />
      
      <mesh geometry={nodes.Cloth_mesh_16.geometry} material={materials.Rib_2X2_468gsm_263076} />

      
      <mesh geometry={nodes.Cloth_mesh_17.geometry} material={materials.Rib_2X2_468gsm_263076} />
      
      <mesh geometry={nodes.Cloth_mesh_18.geometry} material={materials.Sherpa_Shearling_Curly_Fleece_Poly_360gsm_266277} />
      <mesh geometry={nodes.Cloth_mesh_19.geometry} material={materials.Sherpa_Shearling_Curly_Fleece_Poly_360gsm_266284} />
      <mesh geometry={nodes.Cloth_mesh_20.geometry} material={materials.Sherpa_Shearling_Curly_Fleece_Poly_360gsm_266277} />
      
      
      
      
      
      <mesh geometry={nodes.Cloth_mesh_21.geometry} material={materials.Trim_Full_Grain_Leather_256171} />
      <mesh geometry={nodes.Cloth_mesh_22.geometry} material={materials.Trim_Full_Grain_Leather_256171} />
      <mesh geometry={nodes.Cloth_mesh_23.geometry} material={materials.Trim_Full_Grain_Leather_256171} />

{/* small peices */}

      <mesh geometry={nodes.Cloth_mesh_24.geometry} material={materials.Sherpa_Shearling_Curly_Fleece_Poly_360gsm_266277} />
      <mesh geometry={nodes.Cloth_mesh_25.geometry} material={materials.Sherpa_Shearling_Curly_Fleece_Poly_360gsm_266284} />
      <mesh geometry={nodes.Cloth_mesh_26.geometry} material={materials.Sherpa_Shearling_Curly_Fleece_Poly_360gsm_266277} />
     
     
     {/* bottom mesh */}
      <mesh geometry={nodes.Cloth_mesh_27.geometry} material={materials.Sherpa_Shearling_Curly_Fleece_Poly_360gsm_266277} >
      <meshStandardMaterial {...textureprops} />

        </mesh>

 {/* bottom mesh a f */}

        <mesh geometry={nodes.Cloth_mesh_28.geometry} material={materials.Sherpa_Shearling_Curly_Fleece_Poly_360gsm_266284} >

        {selected_part === "Lower Skirt" && (
        <meshStandardMaterial {...textureprops2} />
    )}
    
        </mesh>
      
     
     
    </group>
  )
}

useGLTF.preload('/poncho.glb')
