/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 shirt_model1.glb 
*/

import React, { useEffect, useRef, useState } from 'react'
import { OrbitControls, useGLTF, useTexture } from '@react-three/drei'
import polyster from './second_design.jpg';
import axios from 'axios';
import { Buffer } from 'buffer';
import { useFrame } from '@react-three/fiber';

export default function Model(props) {

{/* 
  let textureprops = useTexture({
    map: polyster,
})
*/}



const[iamge_backend,setBackend_image]=useState()

    const [images, setImages] = useState([]);


  useEffect(() => {
    fetchImages();



    const interval = setInterval(fetchImages, 5000); // Fetch every 5 seconds

    return () => clearInterval(interval);
  }, []);



  useEffect(() => {
      const material = props.material; 
      images.forEach((image) => {
          if (material === image.name) {
              console.log(image.name)
              let source = `data:image/${image.img.contentType};base64,${Buffer.from(image.img.data).toString('base64')}`
              setBackend_image(source);
          }
      });
  }, [props.material, images]); 


  const fetchImages = async () => {
    try {
      const response = await axios.get('http://localhost:5000/send_image');
      setImages(response.data);
    } catch (error) {
      console.error('Error fetching images:', error);
    }
  };




  let textureprops
  if (iamge_backend) {
      textureprops = useTexture({
          map: iamge_backend,
      });
  }

  else {

      textureprops = useTexture({
          map: polyster,
      })

  }
  const selected_part=props.part_selected


  console.log(`selected_part${selected_part}`)

  const { nodes, materials } = useGLTF('/shirt_model1.glb')
  return (
    <group {...props} dispose={null}>


<mesh geometry={nodes.Cloth_mesh.geometry} material={materials.Cotton_Heavy_Canvas_349049} >


{selected_part === "F" && (
  <meshStandardMaterial {...textureprops} />
)}



</mesh>
      <mesh geometry={nodes.Cloth_mesh_1.geometry} material={materials['Default Buttonhole_1751']} />
      <mesh geometry={nodes.Cloth_mesh_2.geometry} material={materials['Default Buttonhole_1751.001']} />
      <mesh geometry={nodes.Cloth_mesh_3.geometry} material={materials['Default Buttonhole_1751.002']} />
      <mesh geometry={nodes.Cloth_mesh_4.geometry} material={materials['Default Buttonhole_1751.003']} />
      <mesh geometry={nodes.Cloth_mesh_5.geometry} material={materials['Default Buttonhole_1751.004']} />
      <mesh geometry={nodes.Cloth_mesh_6.geometry} material={materials['Default Buttonhole_1751.005']} />
      <mesh geometry={nodes.Cloth_mesh_7.geometry} material={materials['Default Buttonhole_1751.006']} />

      
      {/*  back peice */}
      <mesh geometry={nodes.Cloth_mesh_8.geometry} material={materials['Cotton_Heavy_Canvas_349049.001']} >
      
      {selected_part === "Back Shirt" && (
        <meshStandardMaterial {...textureprops} />
    )}
        </mesh>
      
      
      
      {/* back neck */}
        <mesh geometry={nodes.Cloth_mesh_9.geometry} material={materials['Cotton_Heavy_Canvas_349049.002']} >
        
    
      {selected_part === "Back Pieces" && (
        <meshStandardMaterial {...textureprops} />
    )}
        

        </mesh>


{/* back collor */}

      <mesh geometry={nodes.Cloth_mesh_10.geometry} material={materials['Cotton_Heavy_Canvas_349049.003']} >
      {/*<meshStandardMaterial {...textureprops} /> */}

        </mesh>
      <mesh geometry={nodes.Cloth_mesh_11.geometry} material={materials['Default Buttonhole_1751.007']} />
      <mesh geometry={nodes.Cloth_mesh_12.geometry} material={materials['Cotton_Heavy_Canvas_349049.004']} />
      <mesh geometry={nodes.Cloth_mesh_13.geometry} material={materials['Default Buttonhole_1751.008']} />
      <mesh geometry={nodes.Cloth_mesh_14.geometry} material={materials['Default Buttonhole_1751.009']} />
      <mesh geometry={nodes.Cloth_mesh_15.geometry} material={materials['Default Buttonhole_1751.010']} />

      {/* button mesh */}
      <mesh geometry={nodes._mesh.geometry} material={materials['Default Button_1692']} position={[0.007, 1.522, 0.072]} rotation={[1.194, -0.055, -0.176]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes._mesh001.geometry} material={materials['Default Button_1692']} position={[0.008, 1.434, 0.095]} rotation={[1.332, 0.01, -0.145]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes._mesh002.geometry} material={materials['Default Button_1692']} position={[0.007, 1.344, 0.11]} rotation={[1.418, -0.016, -0.025]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes._mesh003.geometry} material={materials['Default Button_1692']} position={[0.006, 1.253, 0.123]} rotation={[1.42, -0.007, 0.028]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes._mesh004.geometry} material={materials['Default Button_1692']} position={[0.006, 1.163, 0.134]} rotation={[1.469, 0.001, 0.07]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes._mesh005.geometry} material={materials['Default Button_1692']} position={[0.007, 1.072, 0.137]} rotation={[1.517, 0.007, 0.048]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes._mesh006.geometry} material={materials['Default Button_1692']} position={[0.295, 0.971, -0.04]} rotation={[1.362, 0.104, 2.764]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes._mesh007.geometry} material={materials['Default Button_1692']} position={[0.332, 0.973, -0.04]} rotation={[1.456, 0.154, -2.086]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes._mesh008.geometry} material={materials['Default Button_1692']} position={[0.319, 1.059, -0.057]} rotation={[1.395, 0.108, -2.426]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes._mesh009.geometry} material={materials['Default Button_1692']} position={[-0.276, 1.045, -0.091]} rotation={[1.38, -0.032, 2.585]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes._mesh010.geometry} material={materials['Default Button_1692']} position={[-0.25, 0.956, -0.079]} rotation={[1.666, -0.058, -2.958]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes._mesh011.geometry} material={materials['Default Button_1692']} position={[-0.287, 0.959, -0.072]} rotation={[1.495, -0.112, 2.187]} scale={[0.55, 1, 0.55]} />
      <mesh geometry={nodes._mesh012.geometry} material={materials['Default Button_1692']} position={[0.006, 1.588, 0.054]} rotation={[1.916, 0.373, -0.472]} scale={[0.55, 1, 0.55]} />
    
    
    
      <mesh geometry={nodes.BindedTrim_1867477.geometry} material={materials['Default Topstitch Copy 1_728436']} />
      <mesh geometry={nodes.BindedTrim_1867623.geometry} material={materials['Default Topstitch Copy 1_728436']} />
      <mesh geometry={nodes.BindedTrim_1867843.geometry} material={materials['Default Topstitch_1868']} />
      <mesh geometry={nodes.BindedTrim_1867921.geometry} material={materials['Default Topstitch Copy 1_728436']} />
      <mesh geometry={nodes.BindedTrim_1868141.geometry} material={materials['Default Topstitch_1868']} />
      <mesh geometry={nodes.BindedTrim_1868235.geometry} material={materials['Default Topstitch Copy 1_728436']} />
      <mesh geometry={nodes.BindedTrim_1868357.geometry} material={materials['Default Topstitch_1868']} />
      <mesh geometry={nodes.BindedTrim_1868465.geometry} material={materials['Default Topstitch Copy 1_728436']} />
      <mesh geometry={nodes.BindedTrim_1868611.geometry} material={materials['Default Topstitch Copy 1_728436']} />
      <mesh geometry={nodes.BindedTrim_1868687.geometry} material={materials['Default Topstitch Copy 1_728436']} />
      <mesh geometry={nodes.BindedTrim_1868758.geometry} material={materials['Default Topstitch Copy 1_728436']} />
      <mesh geometry={nodes.BindedTrim_1868855.geometry} material={materials['Default Topstitch Copy 1_728436']} />
      <mesh geometry={nodes.BindedTrim_1868952.geometry} material={materials['Default Topstitch Copy 1_728436']} />
      <mesh geometry={nodes.BindedTrim_1868994.geometry} material={materials['Default Topstitch Copy 1_728436']} />
      <mesh geometry={nodes.BindedTrim_1869031.geometry} material={materials['Default Topstitch Copy 1_728436']} />
      <mesh geometry={nodes.BindedTrim_1869112.geometry} material={materials['Default Topstitch Copy 1_728436']} />
      <mesh geometry={nodes.BindedTrim_1869193.geometry} material={materials['Default Topstitch Copy 1_728436']} />
      <mesh geometry={nodes.BindedTrim_1869252.geometry} material={materials['Default Topstitch Copy 1_728436']} />
      <mesh geometry={nodes.BindedTrim_1869311.geometry} material={materials['Default Topstitch Copy 1_728436']} />
      <mesh geometry={nodes.BindedTrim_1869417.geometry} material={materials['Default Topstitch Copy 1_728436']} />
      <mesh geometry={nodes.BindedTrim_1869510.geometry} material={materials['Default Topstitch Copy 1_728436']} />
      <mesh geometry={nodes.BindedTrim_1869618.geometry} material={materials['Default Topstitch_1868']} />
      <mesh geometry={nodes.BindedTrim_1869632.geometry} material={materials['Default Topstitch_1868']} />
      <mesh geometry={nodes.BindedTrim_1869646.geometry} material={materials['Default Topstitch_1868']} />
      <mesh geometry={nodes.BindedTrim_1869745.geometry} material={materials['Default Topstitch Copy 1_728436']} />
      <mesh geometry={nodes.BindedTrim_1869867.geometry} material={materials['Default Topstitch_1868']} />
      <mesh geometry={nodes.BindedTrim_1869975.geometry} material={materials['Default Topstitch_1868']} />
      <mesh geometry={nodes.BindedTrim_1869989.geometry} material={materials['Default Topstitch_1868']} />
      <mesh geometry={nodes.BindedTrim_1870003.geometry} material={materials['Default Topstitch_1868']} />
      <mesh geometry={nodes.BindedTrim_1870126.geometry} material={materials['Default Topstitch_1868']} />
    </group>
  )
}

useGLTF.preload('/shirt_model1.glb')
