/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 tshirt_WHITE.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export  default function Model(props) {
  const { nodes, materials } = useGLTF('/tshirt_WHITE.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Stitch_389563.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13528} />
      <mesh geometry={nodes.Stitch_389563_1.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13537} />
      <mesh geometry={nodes.Stitch_389591.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13528} />
      <mesh geometry={nodes.Stitch_389591_1.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13537} />
      <mesh geometry={nodes.Topstitch_1642569.geometry} material={materials.ISO_101_Single_Thread_Chainstitch_2mmoffset_14908} />
      <mesh geometry={nodes.Topstitch_1642569_1.geometry} material={materials.ISO_101_Single_Thread_Chainstitch_2mmoffset_14917} />
      <mesh geometry={nodes.Stitch_386715.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13528} />
      <mesh geometry={nodes.Stitch_386715_1.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13537} />
      <mesh geometry={nodes.Stitch_386743.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13528} />
      <mesh geometry={nodes.Stitch_386743_1.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13537} />
      <mesh geometry={nodes.Stitch_392217.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13528} />
      <mesh geometry={nodes.Stitch_392217_1.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13537} />
      <mesh geometry={nodes.Stitch_392189.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13528} />
      <mesh geometry={nodes.Stitch_392189_1.geometry} material={materials.ISO_406_Two_Needle_Bottom_Coverstitch_13537} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-COL_1'].geometry} material={materials.main_12888} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-COL_2'].geometry} material={materials.main_12888} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-COL_3'].geometry} material={materials.main_12888} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-FRONT_1'].geometry} material={materials.main_12888} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-FRONT_2'].geometry} material={materials.main_12888} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-FRONT_3'].geometry} material={materials.main_12888} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-SLEEVE_2'].geometry} material={materials.main_12888} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-SLEEVE_3'].geometry} material={materials.main_12888} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-SLEEVE_4'].geometry} material={materials.main_12888} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-SLEEVE_1_1'].geometry} material={materials.main_12888} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-SLEEVE_1_2'].geometry} material={materials.main_12888} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-SLEEVE_1_3'].geometry} material={materials.main_12888} />
      <mesh geometry={nodes.Pattern_2903483_1.geometry} material={materials['main Copy 1_12915']} />
      <mesh geometry={nodes.Pattern_2903483_2.geometry} material={materials['main Copy 1_12915']} />
      <mesh geometry={nodes.Pattern_2903483_3.geometry} material={materials['main Copy 1_12915']} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-BACK_1'].geometry} material={materials.main_12888} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-BACK_2'].geometry} material={materials.main_12888} />
      <mesh geometry={nodes['TSHIRTREGULARSSTGM-BACK_3'].geometry} material={materials.main_12888} />
      <mesh geometry={nodes.Pattern_1086885_1.geometry} material={materials.main_12888} />
      <mesh geometry={nodes.Pattern_1086885_2.geometry} material={materials.main_12888} />
      <mesh geometry={nodes.Pattern_1086885_3.geometry} material={materials.main_12888} />
    </group>
  )
}

useGLTF.preload('/tshirt_WHITE.glb')
